// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.IntelliSenseConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SyntaxComponentConfigDlg.IsValid~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SyntaxComponentConfigDlg.btnOK_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SyntaxComponentConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.CodeBlockConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.CodeBlockConfigDlg.Factory")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.CodeBlockConfigDlg.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.SyntaxComponentConfigDlg.Factory")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SyntaxComponentConfigDlg.#ctor(System.Xml.Linq.XElement,System.ComponentModel.Composition.Hosting.CompositionContainer)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.IntelliSenseConfigDlg.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.IntelliSenseConfigDlg.Factory")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SqlConnectionDlg.btnCreate_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.SqlCopyFromIndexConfigDlg.ReflectionIndexDataFactory")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.SqlCopyFromIndexConfigDlg.CommentsIndexDataFactory")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SqlCopyFromIndexConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.SqlResolveReferenceLinksConfigDlg.Factory")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.SqlResolveReferenceLinksConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.ESentCommentsIndexConfigDlg.CommentsIndexDataFactory")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentCommentsIndexConfigDlg.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentCommentsIndexConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.ESentReflectionIndexConfigDlg.ReflectionIndexDataFactory")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentReflectionIndexConfigDlg.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentReflectionIndexConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Tools.BuildComponents.UI.ESentResolveReferenceLinksConfigDlg.Factory")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentResolveReferenceLinksConfigDlg.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Tools.BuildComponents.UI.ESentResolveReferenceLinksConfigDlg.lnkProjectSite_RequestNavigate(System.Object,System.Windows.Navigation.RequestNavigateEventArgs)")]
