//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandcastleBuilder.Package.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SandcastleBuilder.Package.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eric@EWoodruff.us.
        /// </summary>
        internal static string AuthorEMailAddress {
            get {
                return ResourceManager.GetString("AuthorEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Source Properties.
        /// </summary>
        internal static string DocSourceProperties {
            get {
                return ResourceManager.GetString("DocSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Sources.
        /// </summary>
        internal static string DocSourcesNodeCaption {
            get {
                return ResourceManager.GetString("DocSourcesNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.EWoodruff.us.
        /// </summary>
        internal static string EWoodruffURL {
            get {
                return ResourceManager.GetString("EWoodruffURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandcastle Help File Builder.
        /// </summary>
        internal static string PackageTitle {
            get {
                return ResourceManager.GetString("PackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://SHFB.CodePlex.com.
        /// </summary>
        internal static string ProjectURL {
            get {
                return ResourceManager.GetString("ProjectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Properties.
        /// </summary>
        internal static string PropertiesNodeCaption {
            get {
                return ResourceManager.GetString("PropertiesNodeCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Sandcastle {
            get {
                object obj = ResourceManager.GetObject("Sandcastle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandcastle Help File Builder Project Files (*.shfbproj){0}*.shfbproj{1}.
        /// </summary>
        internal static string ShfbProjectFileAssemblyFilter {
            get {
                return ResourceManager.GetString("ShfbProjectFileAssemblyFilter", resourceCulture);
            }
        }
    }
}
