// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~P:Sandcastle.Core.ComponentUtilities.SupportedLanguages")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentUtilities.AssemblyFolder(System.Reflection.Assembly)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentUtilities.SyntaxFiltersFrom(System.Collections.Generic.IEnumerable{Sandcastle.Core.BuildAssembler.SyntaxGenerator.ISyntaxGeneratorMetadata},System.String)~System.Collections.Generic.IEnumerable{Sandcastle.Core.BuildAssembler.SyntaxGenerator.ISyntaxGeneratorMetadata}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.Reflection.AssemblyDetails.FromAssemblyName(System.Reflection.AssemblyName)~Sandcastle.Core.Reflection.AssemblyDetails")]
[assembly: SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Core.Reflection.ReflectionDataSet.BindingRedirection")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.Reflection.ReflectionDataSet.BindingRedirection.FromXml(System.Xml.Linq.XElement)~Sandcastle.Core.Reflection.ReflectionDataSet.BindingRedirection")]
[assembly: SuppressMessage("Design", "CA1010:Generic interface should also be implemented", Justification = "<Pending>", Scope = "type", Target = "~T:Sandcastle.Core.BuildAssembler.CustomContext")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.CustomContext.ResolveFunction(System.String,System.String,System.Xml.XPath.XPathResultType[])~System.Xml.Xsl.IXsltContextFunction")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.CustomContext.CompareDocument(System.String,System.String)~System.Int32")]
[assembly: SuppressMessage("Design", "CA1055:URI-like return values should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.BuildComponent.IMemberIdUrlResolver.ResolveUrlForId(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.StandardDocumentModel.UpdateTypeApiNode(Sandcastle.Core.Reflection.ApiMember)")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.StandardDocumentModel.UpdateGeneralApiNode(Sandcastle.Core.Reflection.ApiMember)")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.StandardDocumentModel.AddMemberListApiElement(System.Xml.XmlWriter,Sandcastle.Core.Reflection.ApiMemberGroup,Sandcastle.Core.Reflection.ApiMember)")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.StandardDocumentModel.AddOverloadListApiElements(System.Xml.XmlWriter,Sandcastle.Core.Reflection.ApiMember)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentAssemblyResolver.CurrentDomain_AssemblyResolve(System.Object,System.ResolveEventArgs)~System.Reflection.Assembly")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(System.ComponentModel.Composition.Hosting.AggregateCatalog,System.String,System.Collections.Generic.HashSet{System.String},System.Boolean,Sandcastle.Core.ComponentAssemblyResolver,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Performance", "CA1827:Do not use Count() or LongCount() when Any() can be used", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentUtilities.AddAssemblyCatalogs(System.ComponentModel.Composition.Hosting.AggregateCatalog,System.String,System.Collections.Generic.HashSet{System.String},System.Boolean,Sandcastle.Core.ComponentAssemblyResolver,System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.BuildComponentUtilities.EvalXPathExpr(System.Xml.XPath.IXPathNavigable,System.Xml.XPath.XPathExpression,System.String[])~System.String")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(Sandcastle.Core.MessageLevel,System.String,System.Object[])")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.BuildComponent.BuildComponentCore.WriteMessage(System.String,Sandcastle.Core.MessageLevel,System.String,System.Object[])")]
[assembly: SuppressMessage("Security", "CA2109:Review visible event handlers", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.BuildAssembler.IBuildAssembler.OnComponentEvent(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Usage", "CA2214:Do not call overridable methods in constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.#ctor")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore.LanguageIdFor(System.String)~System.String")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.SourceContextElement.RequestExampleUrlArgName")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.SourceContextElement.BaseSourceCodeUrlArgName")]
[assembly: SuppressMessage("Design", "CA1054:URI-like parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.SourceContextElement.#ctor(System.String,System.String)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.ComponentUtilities.CreateComponentContainer(System.Collections.Generic.IEnumerable{System.String},Sandcastle.Core.ComponentAssemblyResolver,System.Threading.CancellationToken)~System.ComponentModel.Composition.Hosting.CompositionContainer")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.TransformationArgument.#ctor(System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.Elements.CodeEntityReferenceElement.Render(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore,System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.AutoOutlineElement.Render(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore,System.Xml.Linq.XElement)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.SeeElement.RenderApiTopicLink(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore,System.Xml.Linq.XElement,System.String)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Sandcastle.Core.PresentationStyle.Transformation.Elements.Html.SummaryElement.Render(Sandcastle.Core.PresentationStyle.Transformation.TopicTransformationCore,System.Xml.Linq.XElement)")]
