//=============================================================================
// System  : Sandcastle Help File Builder Visual Studio Package
// File    : Guids.cs
// Author  : Eric Woodruff  (Eric@EWoodruff.us)
// Updated : 04/30/2011
// Note    : Copyright 2011, Eric Woodruff, All rights reserved
// Compiler: Microsoft Visual C#
//
// This file contains various GUIDs for the package
//
// This code is published under the Microsoft Public License (Ms-PL).  A copy
// of the license should be distributed with the code.  It can also be found
// at the project website: http://SHFB.CodePlex.com.  This notice, the
// author's name, and all copyright notices must remain intact in all
// applications, documentation, and source files.
//
// Version     Date     Who  Comments
// ============================================================================
// 1.9.3.0  03/18/2011  EFW  Created the code
//=============================================================================

using System;

namespace SandcastleBuilder.Package
{
    /// <summary>
    /// This class contains various GUID values for the package
    /// </summary>
    /// <remarks>The main package and command set GUIDs are generated by Guids.tt</remarks>
    static partial class GuidList
    {
        /// <summary>The package project factory GUID in string form</summary>
        public const string guidSandcastleBuilderProjectFactoryString = "7CF6DF6D-3B04-46f8-A40B-537D21BCA0B4";
        /// <summary>The package project factory GUID</summary>
        public static readonly Guid guidSandcastleBuilderProjectFactory = new Guid(guidSandcastleBuilderProjectFactoryString);

        /// <summary>Place holder editor factory GUID string</summary>
        public const string guidPlaceHolderEditorFactoryString = "5216041D-390F-4C5F-B78C-38309251BAC3";
        /// <summary>Place holder editor factory GUID</summary>
        public static readonly Guid guidPlaceHolderEditorFactory = new Guid(guidPlaceHolderEditorFactoryString);
    };
}
